# Object Localization and Recognition

### Necessary libraries/modules

In [6]:
import numpy as np
import cv2

from resnet import resnet50
from loading_data import load_train_dataset
from testing import extract_candidate_windows, classify_localize, predict_features, test
from evaluation import read_test_data, evaluate1, evaluate2

from training_svm import train_SVM

In [4]:
TRAIN_FLAG = False

In [3]:
# Class label (unique)
class_labels = np.asarray(['n01615121', 'n02099601', 'n02123159', 'n02129604', 'n02317335',
                           'n02391049', 'n02410509', 'n02422699', 'n02481823', 'n02504458'])

In [2]:
# Creating ResNet50 model
model = resnet50(pretrained=True)

Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /Users/Eray/.cache/torch/checkpoints/resnet50-19c8e357.pth


URLError: <urlopen error [Errno 60] Operation timed out>

### Training

In [5]:
if TRAIN_FLAG is True:
    # Loading the train set (feature vectors and feature label)
    train_features = load_train_dataset(model)

In [ ]:
if TRAIN_FLAG is True:
    # Feature vectors and label for Train set
    train_feature_vectors = [feature['feature_vec'] for feature in train_features]
    train_feature_labels = [feature['label'] for feature in train_features]

In [ ]:
if TRAIN_FLAG is True:
    # One vs all training
    svm_models = train_SVM(train_feature_vectors, train_feature_labels, class_labels)

### Testing

In [ ]:
# Edge detection object ('Edge box' method)
edge_detection = cv2.ximgproc.createStructuredEdgeDetection('../model/model.yml')

In [ ]:
# Testing results
test_predictions, box_boundaries = test(edge_detection, model, svm_models)

In [11]:
test_predictions

array([[ 4, 49],
       [ 4, 26],
       [ 4, 33],
       [ 4, 43],
       [ 4, 43]])

### Evaluation

In [12]:
# Evaluation 1
evaluation1_results = evaluate1(test_predictions, class_labels)

In [13]:
# Evaluation 2
evaluation2_results = evaluate2(test_predictions, box_boundaries, class_labels)

In [14]:
evaluation1_results

[{'label': 0,
  'metrics': {'accuracy': 100.0,
   'TP': 0,
   'FP': 0,
   'FN': 0,
   'TN': 5,
   'recall': 0.0,
   'preicision:': 0.0,
   'NPV': 0.9999999980000001,
   'FPR': 0.0,
   'FDR': 0.0,
   'F1': 0.0,
   'F2': 0.0}},
 {'label': 1,
  'metrics': {'accuracy': 100.0,
   'TP': 0,
   'FP': 0,
   'FN': 0,
   'TN': 5,
   'recall': 0.0,
   'preicision:': 0.0,
   'NPV': 0.9999999980000001,
   'FPR': 0.0,
   'FDR': 0.0,
   'F1': 0.0,
   'F2': 0.0}},
 {'label': 2,
  'metrics': {'accuracy': 100.0,
   'TP': 0,
   'FP': 0,
   'FN': 0,
   'TN': 5,
   'recall': 0.0,
   'preicision:': 0.0,
   'NPV': 0.9999999980000001,
   'FPR': 0.0,
   'FDR': 0.0,
   'F1': 0.0,
   'F2': 0.0}},
 {'label': 3,
  'metrics': {'accuracy': 100.0,
   'TP': 0,
   'FP': 0,
   'FN': 0,
   'TN': 5,
   'recall': 0.0,
   'preicision:': 0.0,
   'NPV': 0.9999999980000001,
   'FPR': 0.0,
   'FDR': 0.0,
   'F1': 0.0,
   'F2': 0.0}},
 {'label': 4,
  'metrics': {'accuracy': 100.0,
   'TP': 0,
   'FP': 0,
   'FN': 0,
   'TN': 5,
 

In [12]:
evaluation2_results

{'overall_accuracy': 1.0,
 'localization_accuracies': array([1.72312782e-05, 8.81000347e-06, 7.52105651e-06, 1.50334132e-05,
        6.87800483e-06])}

In [15]:
import pickle

In [16]:
a = np.array([[1, 2, 3], [2, 4, 5], [3, 4, 6]])

In [17]:
a

array([[1, 2, 3],
       [2, 4, 5],
       [3, 4, 6]])

In [19]:
a[a == 1] = 7

In [20]:
a

array([[7, 2, 3],
       [2, 4, 5],
       [3, 4, 6]])